resources:
  repositories:
    - repository: sourceRepository
      type: github
      endpoint: macreiben-dev
      name: macreiben-dev/team-roster-deploy

variables:
  - group: TeamRoster-Api-Prod

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SSH@0
    displayName: "Create deploy directory"
    inputs:
      sshEndpoint: ssh-team-roster
      runOptions: "commands"
      commands: "mkdir -p ~/deploy_team-roster-container"

  - task: CopyFilesOverSSH@0
    displayName: "Copy compose to deploy directory"
    inputs:
      cleanTargetFolder: true
      sshEndpoint: ssh-team-roster
      contents: "**/*.yml"
      targetFolder: "/home/team-roster-deploy/deploy_team-roster-container"
      readyTimeout: "20000"

  - task: SSH@0
    displayName: "run docker compose"
    inputs:
      sshEndpoint: ssh-team-roster
      runOptions: "inline"
      inline: |
        export SERVER_PORT="$(SERVER_PORT)"
        export APPLICATION_ID="$(SERVER_APPLICATION_ID)"
        export SERVER_API_KEY="$(SERVER_API_KEY)"
        export CLIENT_ID="$(SERVER_CLIENT_ID)"
        export CLIENT_SECRET="$(SERVER_CLIENT_SECRET)"
        export FUSIONAUTH_PORT="$(FUSIONAUTH_PORT)"
        export FUSIONAUTH_SERVERNAME="$(FUSIONAUTH_SERVERNAME)"
        export ISSUER_URL="$(ISSUER_URL)"
        export REDIRECT_URI="$(REDIRECT_URI)"
        export FRONT_APP_ROOT_URL="$(FRONT_APP_ROOT_URL)"
        export FRONT_PORT="$(FRONT_PORT)"
        export TENANT_ID="$(TENANT_ID)"
        sudo -E bash -c 'docker compose -f /home/team-roster-deploy/deploy_team-roster-container/src/docker-compose.yml up -d 2>&1'
