services:
  api:
    image: team-roster-api:latest
    ports:
      - ${SERVER_PORT}:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_API_KEY=${SERVER_API_KEY}
      - CLIENT_ID=${SERVER_CLIENT_ID}
      - CLIENT_SECRET=${SERVER_CLIENT_SECRET}
      - FUSIONAUTH_PORT=${FUSIONAUTH_PORT}
      - FUSIONAUTH_SERVERNAME=${FUSIONAUTH_EXTERNAL_SERVERNAME}
      - FUSIONAUTH_SERVERNAME_FOR_TOKEN=host.docker.internal
      - REDIRECT_URI=${API_OAUTH_REDIRECT_URI}
      - APPLICATION_ID=${APPLICATION_ID}
      - FRONT_APP_ROOT_URL=${FRONT_APP_ROOT_URL}
      - TENANT_ID=${TENANT_ID}
  front:
    image: team-roster-front:latest
    ports:
      - ${FRONT_PORT}:80
    depends_on:
      - api

